// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var slackBotId = "123";

var slackToken = "123";

exports.slackBotId = slackBotId;
exports.slackToken = slackToken;
/* No side effect */
