// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


function addHelpItem(_, _$1, _$2) {
  return /* () */0;
}

function getFirstHelpItem(_, _$1) {
  return /* () */0;
}

exports.addHelpItem = addHelpItem;
exports.getFirstHelpItem = getFirstHelpItem;
/* No side effect */
