// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function decodeType(subTypeString) {
  if (subTypeString === "bot_message") {
    return /* Bot */0;
  } else {
    return /* Human */1;
  }
}

function decode(json) {
  return decodeType(Json_decode.field("subtype", Json_decode.string, json));
}

var SubType = /* module */[
  /* decodeType */decodeType,
  /* decode */decode
];

function decodeType$1(eventString) {
  switch (eventString) {
    case "event_callback" : 
        return /* EventCallback */0;
    case "url_verification" : 
        return /* UrlVerification */1;
    default:
      return /* UnknownEvent */2;
  }
}

function eventType(json) {
  return decodeType$1(Json_decode.field("type", Json_decode.string, json));
}

var Event = /* module */[
  /* decodeType */decodeType$1,
  /* eventType */eventType
];

function decode$1(actionString) {
  if (actionString === "interactive_message") {
    return /* InteractiveMessage */0;
  } else {
    return /* UnknownAction */1;
  }
}

function actionType(json) {
  return decode$1(Json_decode.field("type", Json_decode.string, Json.parseOrRaise(Json_decode.field("payload", Json_decode.string, json))));
}

var Action = /* module */[
  /* decode */decode$1,
  /* actionType */actionType
];

function decodeVerification(json) {
  return /* record */[
          /* challenge */Json_decode.field("challenge", Json_decode.string, json),
          /* token */Json_decode.field("token", Json_decode.string, json)
        ];
}

var Utils = /* module */[/* decodeVerification */decodeVerification];

exports.SubType = SubType;
exports.Event = Event;
exports.Action = Action;
exports.Utils = Utils;
/* No side effect */
