// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Axios = require("axios");
var Config$Drmayday = require("./Config.bs.js");

function sendPayload(payload) {
  var request = {
    url: "https://slack.com/api/chat.postMessage",
    method: "POST",
    headers: {
      Authorization: "Bearer " + Config$Drmayday.slackToken
    },
    data: payload
  };
  return Axios.request(request).then((function (posted) {
                return Promise.resolve(posted);
              }));
}

exports.sendPayload = sendPayload;
/* axios Not a pure module */
