// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Config$Drmayday = require("./Config.bs.js");
var Slack_IO$Drmayday = require("./Slack_IO.bs.js");

function send(_, message) {
  return Slack_IO$Drmayday.sendPayload({
              channel: Config$Drmayday.slackBotId,
              text: message,
              mrkdwn: true
            });
}

function sendWithAttachments(channel, message, attachments) {
  return Slack_IO$Drmayday.sendPayload({
              channel: channel,
              text: message,
              attachments: attachments,
              mrkdwn: true
            });
}

function confirmQueueRemoval(itemId) {
  return "[\n       {\n         \"fallback\": \"Seems like your interface does not suppor attachments.\",\n         \"callback_id\": \"confirm_finished\",\n         \"color\": \"#3AA3E3\",\n         \"attachment_type\": \"default\",\n         \"actions\": [\n           {\n             \"name\": \"remove\",\n             \"text\": \"Yes\",\n             \"type\": \"button\",\n             \"value\": " + (String(itemId) + ",\n           },\n           {\n             \"name\": \"keep\",\n             \"text\": \"No\",\n             \"type\": \"button\",\n             \"value\": \"no\",\n           },\n         ],\n       },\n     ]\n     ");
}

exports.send = send;
exports.sendWithAttachments = sendWithAttachments;
exports.confirmQueueRemoval = confirmQueueRemoval;
/* Slack_IO-Drmayday Not a pure module */
