// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Commands$Drmayday = require("../src/Commands.bs.js");

describe("#Slack.Commands", (function () {
        describe("decodeCommand", (function () {
                Jest.test("help", (function () {
                        return Jest.Expect[/* toEqual */12](/* Help */0, Jest.Expect[/* expect */0](Commands$Drmayday.decodeCommand("help")));
                      }));
                Jest.test("mayday", (function () {
                        return Jest.Expect[/* toEqual */12](/* Mayday */1, Jest.Expect[/* expect */0](Commands$Drmayday.decodeCommand("mayday")));
                      }));
                Jest.test("next", (function () {
                        return Jest.Expect[/* toEqual */12](/* Next */2, Jest.Expect[/* expect */0](Commands$Drmayday.decodeCommand("next")));
                      }));
                Jest.test("next!", (function () {
                        return Jest.Expect[/* toEqual */12](/* NextForce */3, Jest.Expect[/* expect */0](Commands$Drmayday.decodeCommand("next!")));
                      }));
                Jest.test("q", (function () {
                        return Jest.Expect[/* toEqual */12](/* Queue */4, Jest.Expect[/* expect */0](Commands$Drmayday.decodeCommand("q")));
                      }));
                return Jest.test("queue", (function () {
                              return Jest.Expect[/* toEqual */12](/* Queue */4, Jest.Expect[/* expect */0](Commands$Drmayday.decodeCommand("queue")));
                            }));
              }));
        return /* () */0;
      }));

/*  Not a pure module */
