// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

function parseCommand(text) {
  return Caml_array.caml_array_get(text.toLowerCase().split(" ").slice(0, 1), 0);
}

var Utils = /* module */[/* parseCommand */parseCommand];

function decodeCommand(text) {
  var match = parseCommand(text);
  switch (match) {
    case "help" : 
        return /* Help */0;
    case "mayday" : 
        return /* Mayday */1;
    case "next" : 
        return /* Next */2;
    case "next!" : 
        return /* NextForce */3;
    case "q" : 
    case "queue" : 
        return /* Queue */4;
    default:
      return /* Unknown */5;
  }
}

exports.Utils = Utils;
exports.decodeCommand = decodeCommand;
/* No side effect */
