// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Utils$Drmayday = require("./Utils.bs.js");

function decodeCommand(text) {
  var match = Utils$Drmayday.parseCommand(text);
  switch (match) {
    case "help" : 
        return /* Help */0;
    case "mayday" : 
        return /* Mayday */1;
    case "next" : 
        return /* Next */2;
    case "next!" : 
        return /* NextForce */3;
    case "q" : 
    case "queue" : 
        return /* Queue */4;
    default:
      return /* Unknown */5;
  }
}

exports.decodeCommand = decodeCommand;
/* No side effect */
